### ISSUE TITLE
Problemas com teste

### ISSUE THREAD

**Issue by tjoaquini** [gamaacademy/gama-avanade-tryout01#7]
Estou com problemas quando tento executar o teste. Recebo as seguintes mensagens:
![imagem erro](https://user-images.githubusercontent.com/21085469/34584741-1d1f5d34-f184-11e7-93e9-5c6ef39af045.png)

Alguém sabe como posso solucionar?

**Comment by matheusrod92** [comment]
Ola @tjoaquini, você poderia me informar a versão do seu node e npm por favor?
Eu executei o seu repositório aqui e não tive problema com as headers. Visto que estamos utilizando bibliotecas padrões (path, fs) para extrair o content-type pode estar ocorrendo alguma divergência de acordo com as versões do node.
```
> gama-avanade-tryout01@1.0.0 test /home/matt/Temp/gama-avanade-tryout01
> wdio wdio.conf.js


․FFFF

1 passing (126.00s)
4 failing

1) Tryout#1 -  Código HTML&CSS:  O layout desktop deve ser igual ao gabarito:
108033 == 0
running chrome
AssertionError: 108033 == 0
    at layoutTestRunner (/home/matt/Temp/gama-avanade-tryout01/test/AcceptanceTests.js:66:9)
    at Context.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/test/AcceptanceTests.js:19:4)
    at F (/home/matt/Temp/gama-avanade-tryout01/node_modules/core-js/library/modules/_export.js:35:28)

2) Tryout#1 -  Código HTML&CSS:  O layout mobile deve ser igual ao gabarito:
123346 == 0
running chrome
AssertionError: 123346 == 0
    at layoutTestRunner (/home/matt/Temp/gama-avanade-tryout01/test/AcceptanceTests.js:66:9)
    at Context.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/test/AcceptanceTests.js:23:10)
    at F (/home/matt/Temp/gama-avanade-tryout01/node_modules/core-js/library/modules/_export.js:35:28)

3) Tryout#1 -  Formulário de inscrição:  Deve inscrever no processo sem erros:
Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/node_modules/mocha/lib/runnable.js:238:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

4) Tryout#1 -  Formulário de inscrição:  Não deve se inscrever no processo com nome ou email em branco:
Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/node_modules/mocha/lib/runnable.js:238:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by tjoaquini** [comment]
Estou usando o node na versão 9.3.0 e o npm na versão 5.6.0

**Comment by matheusrod92** [comment]
@tjoaquini instalei a sua versão de node e npm e obtive os mesmos erros:

```
> gama-avanade-tryout01@1.0.0 test /home/matt/Temp/gama-avanade-tryout01
> wdio wdio.conf.js


․FFFF_http_outgoing.js:445
      throw new errors.TypeError('ERR_MISSING_ARGS', `header "${key}"`);
      ^

TypeError [ERR_MISSING_ARGS]: The "header "Content-Type"" argument must be specified
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:354:7)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at /home/matt/Temp/gama-avanade-tryout01/server.js:16:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)


1 passing (244.60s)
4 failing

1) Tryout#1 -  Código HTML&CSS:  O layout desktop deve ser igual ao gabarito:
The "header "Content-Type"" argument must be specified
running chrome
TypeError [ERR_MISSING_ARGS]: The "header "Content-Type"" argument must be specified
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:354:7)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at /home/matt/Temp/gama-avanade-tryout01/server.js:16:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

2) Tryout#1 -  Código HTML&CSS:  O layout mobile deve ser igual ao gabarito:
Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:232:19)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

3) Tryout#1 -  Formulário de inscrição:  Deve inscrever no processo sem erros:
The "header "Content-Type"" argument must be specified
running chrome
TypeError [ERR_MISSING_ARGS]: The "header "Content-Type"" argument must be specified
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:354:7)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at /home/matt/Temp/gama-avanade-tryout01/server.js:16:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

4) Tryout#1 -  Formulário de inscrição:  Não deve se inscrever no processo com nome ou email em branco:
Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 60000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/home/matt/Temp/gama-avanade-tryout01/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:232:19)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

A solução é instalar uma versão stable (LTS) do node (8.9.4) e rodar todos os comandos novamente! Desculpa pelo transtorno e vamos verificar qual biblioteca conflitou com essa versão do node.

Aconselho a utilização do **nvm** para fazer o versionamento do node: https://github.com/creationix/nvm

**Comment by tjoaquini** [comment]
@matheusrod92 muito obrigado pela ajuda. Agora consigo rodar os testes por aqui!
